image: python:3.12

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"

cache:
  paths:
    - .uv-cache/
    - .ruff_cache/
    - .pytest_cache/
    - htmlcov/

stages:
  - linting
  - test

before_script:
  - python -V
  - curl -LsSf https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh | sh
  - uv pip install -r requirements.txt

ruff-check:
  stage: linting
  script:
    - ruff check .
    - ruff format --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pytest:
  stage: test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - pytest
  artifacts:
    paths:
      - htmlcov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH