stages:
  - linting
  - test

.python-base: &python-base
  image: python:3.12
  variables:
    UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"
    PATH: "/root/.local/bin:$PATH"  # Add this line to include uv in PATH
  tags:
    - shared-docker-runner
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - curl -LsSf https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh | sh
    - export PATH="/root/.local/bin:$PATH"  # Ensure PATH is updated in this shell session
    - uv pip install -r requirements.txt
  after_script:
    - source .venv/bin/deactivate || true  # Use full path to deactivate
    - rm -rf .venv

ruff-check:
  <<: *python-base
  stage: linting
  cache:
    paths:
      - .uv-cache/
      - .ruff_cache/
  script:
    - ruff check .
    - ruff format --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pytest:
  <<: *python-base
  stage: test
  cache:
    paths:
      - .uv-cache/
      - .pytest_cache/
      - htmlcov/
  script:
    - pytest
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - htmlcov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH