stages:
  - linting
  - test

default:
  image: python:3.12
  tags:
    - shared-docker-runner

.python-base: &python-base
  variables:
    UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"
  before_script:
    - python -m venv .venv
    - . .venv/bin/activate
    - pip install --upgrade pip
    - pip install uv
    - uv pip install -r requirements.txt

ruff-check:
  <<: *python-base
  stage: linting
  cache:
    key: "${CI_COMMIT_REF_SLUG}-ruff"
    paths:
      - .uv-cache/
      - .ruff_cache/
  script:
    - ruff check .
    - ruff format --check .
  after_script:
    - rm -rf .venv
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pytest:
  <<: *python-base
  stage: test
  cache:
    key: "${CI_COMMIT_REF_SLUG}-pytest"
    paths:
      - .uv-cache/
      - .pytest_cache/
      - htmlcov/
  script:
    - pytest
    -
  after_script:
    - rm -rf .venv
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/
      - coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH