image: python:3.12

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"
  VENV_PATH: "$CI_PROJECT_DIR/.venv"

cache:
  paths:
    - .uv-cache/
    - .ruff_cache/
    - .pytest_cache/
    - htmlcov/

stages:
  - linting
  - test

before_script:
  - python3 -V
  - python3 -m venv $VENV_PATH
  - source $VENV_PATH/bin/activate
  - python3 -m pip install -r requirements.txt

after_script:
  - deactivate
  - rm -rf $VENV_PATH

ruff-check:
  stage: linting
  tags:
    - shared-runner-4
    - shared-runner-5
    - shared-runner-6
  script:
    - source $VENV_PATH/bin/activate
    - ruff check .
    - ruff format --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pytest:
  stage: test
  tags:
    - shared-runner-4
    - shared-runner-5
    - shared-runner-6
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - source $VENV_PATH/bin/activate
    - pytest
  artifacts:
    paths:
      - htmlcov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH