name: CI

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

env:
  UV_CACHE_DIR: .uv-cache
  PYTHONUNBUFFERED: 1

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check .
      - run: ruff format --check

  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .uv-cache
            .venv
            .pytest_cache
          key: test-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            test-${{ runner.os }}-main-
            test-${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=.